import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { OpenApiSlGeneratedModule, OpenApiSlGeneratedSharedModule } from './generated/module.js';
import { OpenApiSlValidator, registerValidationChecks } from './open-api-sl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type OpenApiSlAddedServices = {
    validation: {
        OpenApiSlValidator: OpenApiSlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type OpenApiSlServices = LangiumServices & OpenApiSlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const OpenApiSlModule: Module<OpenApiSlServices, PartialLangiumServices & OpenApiSlAddedServices> = {
    validation: {
        OpenApiSlValidator: () => new OpenApiSlValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createOpenApiSlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    OpenApiSl: OpenApiSlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        OpenApiSlGeneratedSharedModule
    );
    const OpenApiSl = inject(
        createDefaultModule({ shared }),
        OpenApiSlGeneratedModule,
        OpenApiSlModule
    );
    shared.ServiceRegistry.register(OpenApiSl);
    registerValidationChecks(OpenApiSl);
    return { shared, OpenApiSl };
}
